### PR TITLE
Slurm 14.11.5 Python3 Compatibility

### PR DESCRIPTION
**Pull request by MikeDacre**
For me, pyslurm works on both python 2.7.5 and python 3.3/3.4 as is, with the exception of the find() commands, which fail. For example pyslurm.job().find('user_id', 5000) fails with the following error:

    In [31]: a.find('user_id', 20043)
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-31-a99217e1171e> in <module>()
    ----> 1 a.find('user_id', 20043)

    pyslurm/pyslurm.pyx in pyslurm.pyslurm.job.find (pyslurm/pyslurm.c:23408)()

    TypeError: expected bytes, str found
    
By changing the function definition from ``find(self, char *name='', val='')`` to ``find(self, name='', val='')`` it is possible to eliminate this error in python3 without affecting performance in python2. I have tested this fix extensively in both python 2.7.5 and python 3.3.4. Furthermore, there is no reason to expect that the C character definiton should be needed in these functions, python's string handlind should actually be more efficient in these cases.

Additionally, compilation failed for me due to the use of spaces on one line of setup.py. I fixed this by switching it to a tab character in a seperate commit.

### CODE REVIEW

**Comment by gingergeeks** [comment]
Mike,
        Thank you for the checks. I think the C declarations in the find function was started as an intention to move the function into a Cython function rather than Python but I cannot remember why now :)

Mark
